
name: Daily Nifty50 AI Update

on:
  schedule:
    - cron: '30 2 * * *'  # Every day at 8:00 AM IST
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug workspace structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files and folders:"
          ls -R

      - name: Run update scripts
        run: |
          python Code/updateohlcv.py
          python Code/UPDATE_NEWS.py
          python Code/update_pcr.py

      - name: Commit and push updated databases
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Databases/*.xlsx
          git commit -m "Update databases [bot]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
